### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by samuel-cavalcanti** [CoppeliaRobotics/zmqRemoteApi#1]
Hello, I write a rust  client zmqRemoteApi [github.com/samuel-cavalcanti/rust_zmqRemoteApi](https://github.com/samuel-cavalcanti/rust_zmqRemoteApi). 
I rewrite  some exemples:

- pController.py
- opencv.py
- simpleTest.py
- synchronousImageTransmission.cpp
- example.cpp 

please check out 😃

**Comment by Coppelia** [comment]
Hello Samuel,
nice! I tested it, and it works great!
Since we have no expertise on Rust at all, best would probably to add references to your repository, from our zmqRemoteApi repository, and documentation. Would that be ok?

**Comment by samuel-cavalcanti** [comment]
Cool, I'm glad to help

**Comment by Coppelia** [comment]
Great, thanks a lot  :)
