### ISSUE TITLE
Missing "sim." in clearStringSignal() in the C++ client

### ISSUE THREAD

**Issue by mfrigerio17** [CoppeliaRobotics/zmqRemoteApi#3]
Hi,
I believe [this line](https://github.com/CoppeliaRobotics/zmqRemoteApi/blob/68ce8da971ea9ac9ddd5ad4e77330e8de3f514c7/clients/cpp/RemoteAPIObjects.cpp#L704) has a mistake, it contains `"clearStringSignal"` instead of `"sim.clearStringSignal"`.

I am not sure whether to open a pull request, as that may be generated code... (??)

**Comment by Coppelia** [comment]
Hi, thanks a lot for mentioning this. Indeed, there is a problem that stems from the fact that CoppeliaSim's calltip for that command was misspelled. The correct file was regenerated.
Cheers

**Comment by mfrigerio17** [comment]
Hello,
If I downloaded and I am using Coppeliasim v4.4.0, what would you suggest to pull in fixes like this one?

If I clone the latest master of this repository and use its C++ sources for the remote api client (rather than the sources available in the coppeliasim root), would the client work with Coppelia 4.4.0?

**Comment by Coppelia** [comment]
You can normally pull the latest, and it should work with CoppeliaSim V4.4 (some new API functions might however not be implemented on CoppeliaSim side in V4.4).
Best of course would be to download V4.5.1, which was released yesterday
