### ISSUE TITLE
New release of Rust ZMQ API

### ISSUE THREAD

**Issue by samuel-cavalcanti** [CoppeliaRobotics/zmqRemoteApi#4]
Hi, I have finished to update the client to  CoppeliaSim 4.5.1 and I noticed that example: [zmqRemoteApiOverview](https://www.coppeliarobotics.com/helpFiles/en/zmqRemoteApiOverview.htm) isn't correct.
This is the correct example: [get_simulation_time.rs](https://github.com/samuel-cavalcanti/rust_zmqRemoteApi/blob/main/examples/get_simulation_time.rs)

**Comment by Coppelia** [comment]
Hi Samuel, thanks a lot. I fixed the code snippet in the user manual according to your example.
Cheers
