### ISSUE TITLE
Callback functionality and lang option

### ISSUE THREAD

**Issue by samuel-cavalcanti** [CoppeliaRobotics/zmqRemoteApi#5]
How are you testing the callback feature ?
```c++
 while (resp.contains("func"))  
    { // We have a callback or a wait:
    }
```
this lang option:
```c++
   j["uuid"] = uuid;
    j["ver"] = VERSION;
    j["lang"] = "c++";
```
what does it ? 
will it be necessary rust option ?

**Comment by Coppelia** [comment]
Hi Samuel, you probably won't be able to easily test that with CoppeliaSim V4.5, I can make a beta of V4.6 available if you tell me which platform you prefer.

- uuid: a unique identifier, so that we can distinguish different client
- VERSION: set to 2 for now
- lang: "rust"

Cheers

**Comment by samuel-cavalcanti** [comment]
I'm a linux user so I would like linux as platform
Thanks for supporting me

**Comment by Coppelia** [comment]
you can find the beta for CoppeliaSim V4.6 [here](https://coppeliarobotics.com/files/beta/CoppeliaSim_Edu_V4_6_0_rev0_Ubuntu22_04.tar.xz)
Feel free to reach out to us if there is any question. Via email is probably a bit easier
Cheers

**Comment by samuel-cavalcanti** [comment]
hi, I'm testing right now, the new API and I think the c++ code is wrong:

https://github.com/CoppeliaRobotics/zmqRemoteApi/blob/master/clients/cpp/RemoteAPIClient.cpp#L135C1-L136C67

I did observe in my logs that the error message is in *rep["err"]*, not in
*rep["error"]*.

Could you recommend a scene that uses a callback function ?
A callback function that it was previous registered  using  the
*client.registerCallback* function method






Em qui., 5 de out. de 2023 às 15:32, Coppelia ***@***.***>
escreveu:

**Comment by Coppelia** [comment]
Hi Samuel, the cpp and other languages should now be up-to-date, except Java. But the reference language is Python and most robust. Make sure to also read the updated [protocol description page](https://github.com/CoppeliaRobotics/zmqRemoteApi/blob/master/PROTOCOL.md)
