### ISSUE TITLE
not connecting on a macOS (with M1)

### ISSUE THREAD

**Issue by giodegas** [CoppeliaRobotics/zmqRemoteApi#7]
this simple program:

    import sys

    sys.path.append("./zmqRemoteApi/clients/python")

    from coppeliasim_zmqremoteapi_client import RemoteAPIClient

    client = RemoteAPIClient()
    sim = client.getObject('.')
    print("done")

never connects ?
Why?
How can I debug it?

Using macOS Ventura 13.6

**Comment by giodegas** [comment]
I discovered that the you have to enable the ZMQ remote API server connectivity

<img width="461" alt="image" src="https://github.com/CoppeliaRobotics/zmqRemoteApi/assets/6838625/32af2e48-2cb5-4997-8944-1cfcb53c54bc">

no wit works!

Unfortunately I could not find any mention of it in the documentation!

**Comment by Coppelia** [comment]
Hello, the ZMQ remote API server should be running by default. Not sure why this is not the case on your system... are you running CoppeliaSim V4.5.1? Please try also CoppeliaSim V4.6 in 1-3 days
