### ISSUE TITLE
Documentation of some API functions (CoppeliaSim 4.6.0)

### ISSUE THREAD

**Issue by samuel-cavalcanti** [CoppeliaRobotics/zmqRemoteApi#8]
Hi, I can't find the documentation of some functions:
```
  22 Unable to find reference for SimIK getFailureDescription
  21 Unable to find reference for sim addReferencedHandle
  20 Unable to find reference for sim getAutoYieldDelay
  19 Unable to find reference for sim getGraphCurve
  18 Unable to find reference for sim getGraphInfo
  17 Unable to find reference for sim getIsRealTimeSimulation
  16 Unable to find reference for sim getObjectAliasRelative
  15 Unable to find reference for sim getSettingBool
  14 Unable to find reference for sim getSettingFloat
  13 Unable to find reference for sim getSettingInt32
  12 Unable to find reference for sim getSettingString
  11 Unable to find reference for sim getThreadId
  10 Unable to find reference for sim handleJointMotion
   9 Unable to find reference for sim readCustomDataBlockEx
   8 Unable to find reference for sim removeReferencedObjects
   7 Unable to find reference for sim setNamedBoolParam
   6 Unable to find reference for sim setNamedFloatParam
   5 Unable to find reference for sim setNamedInt32Param
   4 Unable to find reference for sim testCB  # this can be ignored
   3 Unable to find reference for sim visitTree
   2 Unable to find reference for sim writeCustomDataBlockEx
   1 Unable to find reference for sim yield
  ```
  **sim** is the  the [Regular API reference](https://www.coppeliarobotics.com/helpFiles/index.html)
  **SimIK** is the [IK plugin API reference](https://www.coppeliarobotics.com/helpFiles/en/simIK.htm)

**Comment by samuel-cavalcanti** [comment]
Btw, I scraped the helpFiles to generate my documentation: [docs.rs/coppeliasim_zmq_remote_api](https://docs.rs/coppeliasim_zmq_remote_api/4.6.1/coppeliasim_zmq_remote_api/sim/trait.Sim.html) 
is that okay ?

**Comment by Coppelia** [comment]
Those are I think mostly deprecated functions. The calltips are sometimes however still available for backward compat. It very rarely makes sense to provide other functions (e.g. simIK.\*) than the sim.\* functions to a remote API client. Now, the documentation for non-deprecated functions is generated from [regularApi.xml](https://github.com/CoppeliaRobotics/helpFiles/blob/master/regularApi.xml) which is the reference
