### ISSUE TITLE
Problems with new Python client, sim = client.require('sim')

### ISSUE THREAD

**Issue by AndresMasis** [CoppeliaRobotics/zmqRemoteApi#9]
Hi, when I try to run 

sim = client.require('sim')

from simpleTest.py, I always get the following message:

Exception: No such function: zmqRemoteApi.require

I do not know if I am missing a library or a special configuration.

IMPORTANT NOTE: I am using the previous Python client, the one that used

sim = client.getObject('sim')

and this works perfectly for me, but I do not know why the new client with require() is not working.

Thanks :)

**Comment by fferri** [comment]
When reporting issues please include:

- Operating system and version (e.g. Ubuntu 20.04)
- CoppeliaSim version (e.g. 4.6.0 rev0)
- coppeliasim_zmqremoteapi_client pip version (from `python3 -m pip list`)

**Comment by AndresMasis** [comment]
Operating System: Windows 11
CoppeliaSim version: 4.5.1 rev4
coppeliasim_zmqremote_client:  coppeliasim_zmqremoteapi_client 0.0.5

**Comment by Coppelia** [comment]
Have a look [here](https://forum.coppeliarobotics.com/viewtopic.php?p=39675#p39675)
